// Generated by CoffeeScript 1.12.7
(function() {
  var ApiMate, Application, getHashParams, inputValue, isFilled, makeSearchRegexp, pad, parseQueryString, postErrorTemplate, postSuccessTemplate, preUploadUrl, resultsTemplate, setInputValue;

  $(function() {
    return Application.bindTooltips();
  });

  window.Application = Application = (function() {
    function Application() {}

    Application.bindTooltips = function() {
      var defaultOptions;
      defaultOptions = {
        container: 'body',
        placement: 'top',
        template: '<div class="tooltip results-tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
      };
      return $('.tooltipped').tooltip(defaultOptions);
    };

    return Application;

  })();

  resultsTemplate = "<div class='api-mate-results'> <div class='api-mate-links'> {{#urls}} <div class='api-mate-link-wrapper'> <div class='api-mate-link {{urlClass}}'> <a class='label' href='{{url}}' target='_blank'>GET</a> <a href='#' data-url='{{url}}' class='tooltipped label' title='Send \"{{name}}\" using a POST request' data-api-mate-post='{{name}}'>POST</a> <span class='api-mate-method-name'>{{description}}</span> <a href='{{url}}' target='_blank'>{{url}}</a> </div> </div> {{/urls}} </div> <div class='api-mate-result-title'> <h5 class='label-title'>Results {{title}}:</h5> </div> </div>";

  postSuccessTemplate = "<pre>{{response}}</pre>";

  postErrorTemplate = "<p>Server responded with status: <code>{{status}}: {{statusText}}</code>.</p> {{#response}} <p>Content:</p> <pre>{{response}}</pre> {{/response}} {{^response}} <p>Content: <code>-- no content --</code></p> {{/response}} <p>If you don't know the reason for this error, check these possibilities:</p> <ul> <li> Your server does not allow <strong>cross-domain requests</strong>. By default BigBlueButton and Mconf-Live <strong>do not</strong> allow cross-domain requests, so you have to enable it to test this request via POST. Check our <a href=\"https://github.com/mconf/api-mate/tree/master#allow-cross-domain-requests\">README</a> for instructions on how to do it. </li> <li> This API method cannot be accessed via POST. </li> <li> Your server is down or malfunctioning. Log into it and check if everything is OK with <code>bbb-conf --check</code>. </li> <ul>";

  preUploadUrl = "<?xml version='1.0' encoding='UTF-8'?> <modules> <module name='presentation'> {{#urls}} <document url='{{url}}' /> {{/urls}} </module> </modules>";

  $(function() {
    var apiMate, placeholders;
    placeholders = {
      results: '#api-mate-results',
      modal: '#post-response-modal'
    };
    apiMate = new ApiMate(placeholders);
    apiMate.start();
    return $('#api-mate-results').on('api-mate-urls-added', function() {
      return Application.bindTooltips();
    });
  });

  window.ApiMate = ApiMate = (function() {
    function ApiMate(placeholders1, templates) {
      var base, base1, base2, base3;
      this.placeholders = placeholders1;
      this.templates = templates;
      this.updatedTimer = null;
      this.urls = [];
      if (this.placeholders == null) {
        this.placeholders = {};
      }
      if (this.templates == null) {
        this.templates = {};
      }
      if ((base = this.templates)['results'] == null) {
        base['results'] = resultsTemplate;
      }
      if ((base1 = this.templates)['postSuccess'] == null) {
        base1['postSuccess'] = postSuccessTemplate;
      }
      if ((base2 = this.templates)['postError'] == null) {
        base2['postError'] = postErrorTemplate;
      }
      if ((base3 = this.templates)['preUpload'] == null) {
        base3['preUpload'] = preUploadUrl;
      }
      this.debug = false;
      this.urlsLast = null;
    }

    ApiMate.prototype.start = function() {
      return this.loadServers((function(_this) {
        return function() {
          return _this._startAfterServers();
        };
      })(this));
    };

    ApiMate.prototype.loadServers = function(callback) {
      return $.getJSON('servers.json').done((function(_this) {
        return function(servers) {
          var $option, $select, j, len, server;
          $select = $("[data-api-mate-server='url']");
          $select.empty();
          for (j = 0, len = servers.length; j < len; j++) {
            server = servers[j];
            $option = $('<option>').val(server.url).text(server.name).attr('data-secret', server.secret || '');
            $select.append($option);
          }
          _this._updateSecretFromSelected();
          return typeof callback === "function" ? callback() : void 0;
        };
      })(this)).fail((function(_this) {
        return function() {
          console.warn('Could not load servers.json – server dropdown will be empty.');
          return typeof callback === "function" ? callback() : void 0;
        };
      })(this));
    };

    ApiMate.prototype._updateSecretFromSelected = function() {
      var $select, secret;
      $select = $("[data-api-mate-server='url']");
      secret = $select.find('option:selected').attr('data-secret');
      if (secret != null) {
        return $("[data-api-mate-server='salt']").val(secret);
      }
    };

    ApiMate.prototype._startAfterServers = function() {
      this.initializeMenu();
      $("[data-api-mate-param*='meetingID']").on("keyup", function() {
        return $("[data-api-mate-param*='name']").val($(this).val());
      });
      $("[data-api-mate-server='url']").on("change", (function(_this) {
        return function() {
          return _this._updateSecretFromSelected();
        };
      })(this));
      $("[data-api-mate-param]").on("change keyup", (function(_this) {
        return function(e) {
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-server]").on("change keyup", (function(_this) {
        return function(e) {
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-special-param]").on("change keyup", (function(_this) {
        return function(e) {
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-sha]").on("click", (function(_this) {
        return function(e) {
          $("[data-api-mate-sha]").removeClass('active');
          $(e.target).addClass('active');
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-expand]").on("click", (function(_this) {
        return function() {
          var selected;
          selected = !$("[data-api-mate-expand]").hasClass("active");
          _this.expandLinks(selected);
          return true;
        };
      })(this));
      $("[data-api-mate-clear]").on("click", (function(_this) {
        return function(e) {
          _this.clearAllFields();
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-randomize]").on("click", (function(_this) {
        return function(e) {
          _this.initializeMenu();
          _this.generateUrls();
          return _this.addUrlsToPage(_this.urls);
        };
      })(this));
      $("[data-api-mate-debug]").on("click", (function(_this) {
        return function() {
          var selected;
          selected = !$("[data-api-mate-debug]").hasClass("active");
          _this.debug = selected;
          return true;
        };
      })(this));
      this.generateUrls();
      this.addUrlsToPage(this.urls);
      this.bindPostRequests();
      return this.bindSearch();
    };

    ApiMate.prototype.initializeMenu = function() {
      var name, user, vbridge;
      vbridge = "7" + pad(Math.floor(Math.random() * 10000 - 1).toString(), 4);
      $("[data-api-mate-param*='voiceBridge']").val(vbridge);
      name = "random-" + Math.floor(Math.random() * 10000000).toString();
      $("[data-api-mate-param*='name']").val(name);
      $("[data-api-mate-param*='meetingID']").val(name);
      $("[data-api-mate-param*='recordID']").val(name);
      user = "User " + Math.floor(Math.random() * 10000000).toString();
      $("[data-api-mate-param*='fullName']").val(user);
      return this.setMenuValuesFromURL();
    };

    ApiMate.prototype.addUrlsToPage = function(urls) {
      var desc, html, isEqual, item, j, len, opts, placeholder;
      isEqual = (urls != null) && (this.urlsLast != null) && (JSON.stringify(urls) === JSON.stringify(this.urlsLast));
      if (isEqual) {
        return;
      }
      this.urlsLast = _.map(urls, _.clone);
      placeholder = $(this.placeholders['results']);
      for (j = 0, len = urls.length; j < len; j++) {
        item = urls[j];
        desc = item.description;
        if (desc.match(/recording/i)) {
          item.urlClass = "api-mate-url-recordings";
        } else if (desc.match(/mobile/i)) {
          item.urlClass = "api-mate-url-from-mobile";
        } else if (desc.match(/custom call/i)) {
          item.urlClass = "api-mate-url-custom-call";
        } else {
          item.urlClass = "api-mate-url-standard";
        }
      }
      opts = {
        title: new Date().toTimeString(),
        urls: urls
      };
      html = Mustache.to_html(this.templates['results'], opts);
      $('.results-tooltip').remove();
      $(placeholder).html(html);
      this.expandLinks($("[data-api-mate-expand]").hasClass("active"));
      $('.api-mate-results', this.placeholders['results']).addClass("updated");
      clearTimeout(this.updatedTimer);
      this.updatedTimer = setTimeout((function(_this) {
        return function() {
          return $('.api-mate-results', _this.placeholders['results']).removeClass("updated");
        };
      })(this), 300);
      return $(this.placeholders['results']).trigger('api-mate-urls-added');
    };

    ApiMate.prototype.getApi = function() {
      var j, len, level, opts, server, shaLevels;
      server = {};
      server.url = $("[data-api-mate-server='url']").val();
      server.salt = $("[data-api-mate-server='salt']").val();
      server.url = server.url.replace(/(\/api)?\/?$/, '/api');
      server.name = server.url;
      opts = {};
      shaLevels = ['sha1', 'sha256', 'sha384', 'sha512'];
      for (j = 0, len = shaLevels.length; j < len; j++) {
        level = shaLevels[j];
        if ($("[data-api-mate-sha='" + level + "']").hasClass("active")) {
          opts.shaType = level;
        }
      }
      return new BigBlueButtonApi(server.url, server.salt, this.debug, opts);
    };

    ApiMate.prototype.generateUrls = function() {
      var _elem, api, customCalls, customParams, j, k, len, len1, len2, len3, line, lines, m, n, name, paramName, paramValue, params, ref, separator;
      params = {};
      customParams = {};
      $('[data-api-mate-param]').each(function() {
        var $elem, attr, attrs, j, len, value;
        $elem = $(this);
        attrs = $elem.attr('data-api-mate-param').split(',');
        value = inputValue($elem);
        if ((attrs != null) && (value != null)) {
          for (j = 0, len = attrs.length; j < len; j++) {
            attr = attrs[j];
            params[attr] = value;
          }
        }
        return true;
      });
      lines = inputValue("textarea[data-api-mate-special-param='meta']");
      if (lines != null) {
        lines = lines.replace(/\r\n/g, "\n").split("\n");
        for (j = 0, len = lines.length; j < len; j++) {
          line = lines[j];
          separator = line.indexOf("=");
          if (separator >= 0) {
            paramName = line.substring(0, separator);
            paramValue = line.substring(separator + 1, line.length);
            params["meta_" + paramName] = paramValue;
          }
        }
      }
      lines = inputValue("textarea[data-api-mate-special-param='custom-params']");
      if (lines != null) {
        lines = lines.replace(/\r\n/g, "\n").split("\n");
        for (k = 0, len1 = lines.length; k < len1; k++) {
          line = lines[k];
          separator = line.indexOf("=");
          if (separator >= 0) {
            paramName = line.substring(0, separator);
            paramValue = line.substring(separator + 1, line.length);
            params["custom_" + paramName] = paramValue;
            customParams["custom_" + paramName] = paramValue;
          }
        }
      }
      lines = inputValue("textarea[data-api-mate-special-param='custom-calls']");
      if (lines != null) {
        lines = lines.replace(/\r\n/g, "\n").split("\n");
        customCalls = lines;
      } else {
        customCalls = null;
      }
      api = this.getApi();
      this.urls = [];
      _elem = function(name, desc, url) {
        return {
          name: name,
          description: desc,
          url: url
        };
      };
      ref = api.availableApiCalls();
      for (m = 0, len2 = ref.length; m < len2; m++) {
        name = ref[m];
        if (name === 'join') {
          params['password'] = params['moderatorPW'];
          this.urls.push(_elem(name, name + " as moderator", api.urlFor(name, params)));
          params['password'] = params['attendeePW'];
          this.urls.push(_elem(name, name + " as attendee", api.urlFor(name, params)));
          params['password'] = params['moderatorPW'];
        } else {
          this.urls.push(_elem(name, name, api.urlFor(name, params)));
        }
      }
      if (customCalls != null) {
        for (n = 0, len3 = customCalls.length; n < len3; n++) {
          name = customCalls[n];
          this.urls.push(_elem(name, "custom call: " + name, api.urlFor(name, customParams, false)));
        }
      }
      params['password'] = params['moderatorPW'];
      this.urls.push(_elem("join", "mobile call: join as moderator", api.setMobileProtocol(api.urlFor("join", params))));
      params['password'] = params['attendeePW'];
      return this.urls.push(_elem("join", "mobile call: join as attendee", api.setMobileProtocol(api.urlFor("join", params))));
    };

    ApiMate.prototype.clearAllFields = function() {
      return $("[data-api-mate-param]").each(function() {
        $(this).val("");
        return $(this).attr("checked", null);
      });
    };

    ApiMate.prototype.expandLinks = function(selected) {
      if (selected) {
        return $(".api-mate-link", this.placeholders['results']).addClass('expanded');
      } else {
        return $(".api-mate-link", this.placeholders['results']).removeClass('expanded');
      }
    };

    ApiMate.prototype.bindPostRequests = function() {
      var _apiMate;
      _apiMate = this;
      return $(document).on('click', 'a[data-api-mate-post]', function(e) {
        var $target, contentType, data, href, method;
        $target = $(this);
        href = $target.attr('data-url');
        method = $target.attr('data-api-mate-post');
        data = _apiMate.getPostData(method);
        contentType = _apiMate.getPostContentType(method);
        $('[data-api-mate-post]').addClass('disabled');
        $.ajax({
          url: href,
          type: "POST",
          crossDomain: true,
          contentType: contentType,
          dataType: "xml",
          data: data,
          complete: function(jqxhr, status) {
            var html, modal, opts, postError, postSuccess;
            modal = _apiMate.placeholders['modal'];
            postSuccess = _apiMate.templates['postSuccess'];
            postError = _apiMate.templates['postError'];
            if (jqxhr.status === 200) {
              $('.modal-header', modal).removeClass('alert-danger');
              $('.modal-header', modal).addClass('alert-success');
              html = Mustache.to_html(postSuccess, {
                response: jqxhr.responseText
              });
              $('.modal-body', modal).html(html);
            } else {
              $('.modal-header h4', modal).text('Ooops!');
              $('.modal-header', modal).addClass('alert-danger');
              $('.modal-header', modal).removeClass('alert-success');
              opts = {
                status: jqxhr.status,
                statusText: jqxhr.statusText
              };
              if (!_.isEmpty(jqxhr.responseText)) {
                opts['response'] = jqxhr.responseText;
              }
              html = Mustache.to_html(postError, opts);
              $('.modal-body', modal).html(html);
            }
            $(modal).modal({
              show: true
            });
            return $('[data-api-mate-post]').removeClass('disabled');
          }
        });
        e.preventDefault();
        return false;
      });
    };

    ApiMate.prototype.getPostData = function(method) {
      var api, checksum, opts, query, urls;
      if (method === 'create') {
        urls = inputValue("textarea[data-api-mate-param='pre-upload']");
        if (urls != null) {
          urls = urls.replace(/\r\n/g, "\n").split("\n");
          urls = _.map(urls, function(u) {
            return {
              url: u
            };
          });
          opts = {
            urls: urls
          };
          return Mustache.to_html(this.templates['preUpload'], opts);
        }
      } else if (method === 'setConfigXML') {
        if (isFilled("textarea[data-api-mate-param='configXML']")) {
          api = this.getApi();
          query = "configXML=" + (api.encodeForUrl($("#input-config-xml").val()));
          query += "&meetingID=" + (api.encodeForUrl($("#input-mid").val()));
          checksum = api.checksum('setConfigXML', query);
          query += "&checksum=" + checksum;
          return query;
        }
      }
    };

    ApiMate.prototype.getPostContentType = function(method) {
      if (method === 'create') {
        return 'application/xml; charset=utf-8';
      } else if (method === 'setConfigXML') {
        return 'application/x-www-form-urlencoded';
      }
    };

    ApiMate.prototype.bindSearch = function() {
      var _apiMate;
      _apiMate = this;
      return $(document).on('keyup', '[data-api-mate-search-input]', function(e) {
        var $target, search, searchTerm;
        $target = $(this);
        searchTerm = inputValue($target);
        search = function() {
          var $elem, attr, attrs, j, len, ref, ref1, searchRe, visible;
          $elem = $(this);
          if ((searchTerm != null) && !_.isEmpty(searchTerm.trim())) {
            visible = false;
            searchRe = makeSearchRegexp(searchTerm);
            attrs = ((ref = $elem.attr('data-api-mate-param')) != null ? ref.split(',') : void 0) || [];
            attrs = attrs.concat(((ref1 = $elem.attr('data-api-mate-search')) != null ? ref1.split(',') : void 0) || []);
            for (j = 0, len = attrs.length; j < len; j++) {
              attr = attrs[j];
              if (attr.match(searchRe)) {
                visible = true;
              }
            }
          } else {
            visible = true;
          }
          if (visible) {
            $elem.parents('.form-group').show();
          } else {
            $elem.parents('.form-group').hide();
          }
          return true;
        };
        $('[data-api-mate-param]').each(search);
        return $('[data-api-mate-special-param]').each(search);
      });
    };

    ApiMate.prototype.setMenuValuesFromURL = function() {
      var prop, query, query2, results, value;
      query = getHashParams();
      query2 = parseQueryString(window.location.search.substring(1));
      query = _.extend(query2, query);
      if (query.server != null) {
        $("[data-api-mate-server='url']").val(query.server);
        delete query.server;
      }
      if (query.salt != null) {
        $("[data-api-mate-server='salt']").val(query.salt);
        delete query.salt;
      }
      if (query.sharedSecret != null) {
        $("[data-api-mate-server='salt']").val(query.sharedSecret);
        delete query.sharedSecret;
      }
      if (query.secret != null) {
        $("[data-api-mate-server='salt']").val(query.secret);
        delete query.secret;
      }
      results = [];
      for (prop in query) {
        value = query[prop];
        setInputValue($("[data-api-mate-param='" + prop + "']"), value);
        results.push(setInputValue($("[data-api-mate-special-param='" + prop + "']"), value));
      }
      return results;
    };

    return ApiMate;

  })();

  inputValue = function(selector) {
    var $elem, ref, type, value;
    $elem = $(selector);
    type = $elem.attr('type') || ((ref = $elem.prop('tagName')) != null ? ref.toLowerCase() : void 0);
    switch (type) {
      case 'checkbox':
        return $elem.is(":checked");
      default:
        value = $elem.val();
        if ((value != null) && !_.isEmpty(value.trim())) {
          return value;
        } else {
          return null;
        }
    }
  };

  setInputValue = function(selector, value) {
    var $elem, ref, type, val;
    $elem = $(selector);
    type = $elem.attr('type') || ((ref = $elem.prop('tagName')) != null ? ref.toLowerCase() : void 0);
    switch (type) {
      case 'checkbox':
        val = (value != null) && value !== '0' && value !== 0;
        return $elem.prop('checked', val);
      default:
        return $elem.val(value);
    }
  };

  isFilled = function(field) {
    var value;
    value = $(field).val();
    return (value != null) && !_.isEmpty(value.trim());
  };

  pad = function(num, size) {
    var j, ref, s;
    s = '';
    for (j = 0, ref = size - 1; 0 <= ref ? j <= ref : j >= ref; 0 <= ref ? j++ : j--) {
      s += '0';
    }
    s += num;
    return s.substr(s.length - size);
  };

  parseQueryString = function(queryString) {
    var i, l, params, queries, temp;
    params = {};
    if ((queryString != null) && !_.isEmpty(queryString)) {
      queries = queryString.split("&");
    } else {
      queries = [];
    }
    i = 0;
    l = queries.length;
    while (i < l) {
      temp = queries[i].split('=');
      params[temp[0]] = temp[1];
      i++;
    }
    return params;
  };

  makeSearchRegexp = function(term) {
    var terms;
    terms = term.split(" ");
    terms = _.filter(terms, function(t) {
      return !_.isEmpty(t.trim());
    });
    terms = _.map(terms, function(t) {
      return ".*" + t + ".*";
    });
    terms = terms.join('|');
    return new RegExp(terms, "i");
  };

  getHashParams = function() {
    var a, d, e, hashParams, q, r;
    hashParams = {};
    a = /\+/g;
    r = /([^&;=]+)=?([^&;]*)/g;
    d = function(s) {
      return decodeURIComponent(s.replace(a, " "));
    };
    q = window.location.hash.substring(1);
    while (e = r.exec(q)) {
      hashParams[d(e[1])] = d(e[2]);
    }
    return hashParams;
  };

}).call(this);
